/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import enumEntidade.ContaEnum;
import view.retab.FormProgressoRetab;
import view.retab.FormAtualizacaoRetab;
import rotinasPortal.AcessoOutrosBancos;
import rotinasPortal.CriarSolicitacaoLevPortal;
import rotinasPortal.EfetivarLevantamento;
import rotinasPortal.ExtratoBanrisul;
import rotinasPortal.ExtratoCef;
import rotinasPortal.IncluirBeneficiario;
import rotinasSisbb.ColetaAgenciaDetentoraDjo;
import rotinasPortal.VerificarSituacaoPortalJuridico;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisbbgeneric.Janela3270;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import rotinasPortal.AnaliseLiberacaoCustoTarifa;
import rotinasPortal.ColetaResgateDepJudicial;
import rotinasPortal.ComplementarDeposito;
import rotinasPortal.ComplementarDepositoEfetivacao;
import rotinasPortal.DespacharCustoTarifa;
import rotinasPortal.DestinarDesfavoravelDanoMoralDJO;
import rotinasPortal.DestinarDesfavoravelPoupancaDJO;
import rotinasPortal.DevolverAgencia;
import rotinasPortal.EfetivarCustoTarifa;
import rotinasPortal.IncluirSolicitacaoTarifa;
import rotinasPortal.LeituraBaseDadosWEB;
import rotinasPortal.VerificarRetornoAgencia;
import rotinasPortal.LeituraSaldoContabilPortal;
import rotinasPortal.VerificarSituacaoResgateBaseCpj;
import rotinasPortal.VerificarSituacaoSolicitacaoTarifa;
import rotinasSisbb.ColetaConta99;
import rotinasSisbb.ColetaDadosUsuarios;
import rotinasSisbb.ColetaSaldoDjoBaseWeb;
import rotinasSisbb.ColetarDadosDJOSequencial;
import rotinasSisbb.ComplementoTFI;
import rotinasSisbb.PartidaEgtCustoTarifa;
import rotinasSisbb.TratarInedito;
import rotinasSisbb.VerificarSituacaoPartidaEgt;
import sisbbgeneric.PropriedadesPadraoSISBB;

/**
 *
 * @author F4618689
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public FormPrincipal() {
        //setPropriedades();
        initComponents();

        URL caminhoIcone = getClass().getResource("/imagens/banco do brasil.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);

    }

    public void setPropriedades() {

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu18ContaJudicial = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem43_retag691 = new javax.swing.JMenuItem();
        jMenuItem47_compe691 = new javax.swing.JMenuItem();
        jMenu23_retag700 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49_compe700 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        jMenuItem29.setText("jMenuItem29");

        jMenu15.setText("jMenu15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(656, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu3.setText("Levantamentos");

        jMenuItem2.setText("Incluir Solicitação de Levantamento");
        jMenuItem2.setActionCommand("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem14.setText("Incluir Solicitação de Tarifa");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem26.setText("Incluir Solicitacao de Inédito");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem26);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Rotinas Sisbb");

        jMenu1.setText("Tratar Inéditos");

        jMenuItem1.setText("Coletar a detentora do depósito");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem27.setText("Tratar");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenu2.add(jMenu1);

        jMenu13.setText("Rotinas DJO base Web");

        jMenuItem31.setText("Coletar Saldo DJO");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem31);

        jMenu2.add(jMenu13);

        jMenu18ContaJudicial.setText("Rotinas Favoráveis BB");

        jMenu22.setText("Conta 691");

        jMenuItem43_retag691.setText("1 - Captura RETAG 691");
        jMenuItem43_retag691.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43_retag691ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem43_retag691);

        jMenuItem47_compe691.setText("2 - Complemento TFI 691");
        jMenuItem47_compe691.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47_compe691ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem47_compe691);

        jMenu18ContaJudicial.add(jMenu22);

        jMenu23_retag700.setText("Conta 700");

        jMenuItem48.setText("1- Captura RETAG 700");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu23_retag700.add(jMenuItem48);

        jMenuItem49_compe700.setText("2 - Complemento TFI 700");
        jMenuItem49_compe700.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49_compe700ActionPerformed(evt);
            }
        });
        jMenu23_retag700.add(jMenuItem49_compe700);

        jMenu18ContaJudicial.add(jMenu23_retag700);

        jMenu2.add(jMenu18ContaJudicial);

        jMenuItem23.setText("Efetuar Partida EGT Custo/Tarifa");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem24.setText("Verificar Situação da Partida EGT");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("GSV");
        jMenu4.setActionCommand("Consulta");
        jMenuBar1.add(jMenu4);

        jMenu8.setText("Ferramentas");

        jMenuItem3.setText("Sair do Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem7.setText("Acesso CEF");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem11.setText("Download Extrato Banrisul");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem4.setText("Base Murchada");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem12.setText("Cadastrar Usuario");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Download Extrato CEF");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jMenuItem15.setText("Solicitar Extrato CEF");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenuItem25.setText("Portal Rejud");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem25);

        jMenu11.setText("Usuarios");

        jMenuItem16.setText("Atualizar dados de usuários");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem16);

        jMenu8.add(jMenu11);

        jMenu18.setText("Atualização Base");

        jMenu21.setText("Outros Bancos");

        jMenuItem40.setText("Atualizar base Outros Bancos");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem40);

        jMenuItem44.setText("Carregar arquivos para upload");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem44);

        jMenu18.add(jMenu21);

        jMenu19.setText("REJUD");

        jMenuItem33.setText("Lista Portal Jurídico DJO");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem33);

        jMenuItem43.setText("Atualizar base Web DJO");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem43);

        jMenu18.add(jMenu19);

        jMenu20.setText("RETAB");

        jMenuItem45.setText("Lista PJ DJO - RETAB");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem45);

        jMenuItem46.setText("Atualizar Base Web DJO - RETAB");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem46);

        jMenu18.add(jMenu20);

        jMenu8.add(jMenu18);

        jMenuBar1.add(jMenu8);

        jMenu5.setText("Configuração");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Rotinas Portal");

        jMenuItem5.setText("Contabilizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem28.setText("Complementar Depósitos");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem28);

        jMenuItem8.setText("Verificar Situação  da Solicitação Levantamento");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Incluir solicitação de Levantamento Portal Jurídico");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem6.setText("Incluir Parte no Portal Jurídico");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenu10.setText("Solicitação de Tarifa");

        jMenuItem17.setText("Incluir Solicitação de Custo/Tarifa");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenuItem20.setText("Efetuar Analise/Liberação de Tarifa/Custo");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenuItem21.setText("Efetivar Tarifa/Custo");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem21);

        jMenuItem19.setText("Verificar Situação da Tarifa/Custo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem19);

        jMenuItem22.setText("Despachar Tarifa/Custo");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem22);

        jMenu6.add(jMenu10);

        jMenu12.setText("Rotinas Base Web");

        jMenuItem30.setText("Verificar Retorno Agência");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem30);

        jMenuItem32.setText("Leitura de Saldo Contábil");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem32);

        jMenuItem34.setText("Ler dados Portal Base WEB");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem34);

        jMenu6.add(jMenu12);

        jMenu14.setText("Coletas Resgates");

        jMenuItem35.setText("Coleta Sequencial");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem35);

        jMenuItem36.setText("Coleta DJO Sequencial");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem36);

        jMenuItem41.setText("Sincronizar situação resgates");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem41);

        jMenu6.add(jMenu14);

        jMenu16.setText("Destinação Massificada DJO");

        jMenuItem37.setText("Destinar Desfavorável Dano Moral");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem37);

        jMenuItem38.setText("Destinar Desfavorável Poupança");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem38);

        jMenuItem39.setText("Devolver Agência");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem39);

        jMenu6.add(jMenu16);

        jMenu17.setText("Efetivação de depósito");

        jMenuItem42.setText("Complementar depósito efetivado");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem42);

        jMenu6.add(jMenu17);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Relatórios");

        jMenuItem10.setText("Minhas Solicitações de Levantamento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem18.setText("Minhas Solicitações de Tarifa");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("Mais Opções");
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    ColetaAgenciaDetentoraDjo t = new ColetaAgenciaDetentoraDjo();
                    t.inicioRotinaSisbb(sisbb, "DJO");

                    sisbb.rotinaEncerramento();

                    JOptionPane.showMessageDialog(null, "Agência detentora do Djo coletada!");
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        };
        thread.start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        frmSolicitacaoLevantamento jc = new frmSolicitacaoLevantamento();
        jc.setTitle("Solicitacao de Levantamento");
        jc.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        int i = JOptionPane.showConfirmDialog(null, "Deseja efetuar a destinação dos registros de solicitação de levantamento?",
                "Contabilização de resgate", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.NO_OPTION) {

            return;
        }

        this.setTitle("Rotina de contabilização de resgate em execução....");
        EfetivarLevantamento v = new EfetivarLevantamento();
        v.start();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        VerificarSituacaoPortalJuridico v = new VerificarSituacaoPortalJuridico();

        this.setTitle("Rotina de verificação da situação da solicitação de levantamento em execução.....");

        v.start();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CriarSolicitacaoLevPortal criarSolicitacaoLevPortal = new CriarSolicitacaoLevPortal();

        this.setTitle("Rotina de inclusão de solicitação de levantamento em execução.....");

        criarSolicitacaoLevPortal.start();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        IncluirBeneficiario incluir = new IncluirBeneficiario();

        this.setTitle("Rotina de inclusão de parte no processo  em execução.....");
        incluir.start();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        FormTabLevantamento formLevantamento = new FormTabLevantamento(this, rootPaneCheckingEnabled);
        formLevantamento.setTitle("Solicitação de Levantamento");
        formLevantamento.setVisible(true);

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        AcessoOutrosBancos acessoCef = new AcessoOutrosBancos();
        acessoCef.logarCef();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ExtratoBanrisul ex = new ExtratoBanrisul();
        try {
            ex.downloadExtrato();
        } catch (Exception ex1) {
            JOptionPane.showMessageDialog(null, ex1);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        view.FormBaseMurchada formBaseMurchada = new view.FormBaseMurchada(null, rootPaneCheckingEnabled);
        formBaseMurchada.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        FormCadastro formCadastro = new FormCadastro(this, rootPaneCheckingEnabled);
        formCadastro.setTitle("Cadastro de novo usuário");
        formCadastro.setVisible(true);

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ExtratoCef extratocef = new ExtratoCef();
        extratocef.start();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FormSolicitacaoExtrato frm = new FormSolicitacaoExtrato(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        frmLogin flogin = new frmLogin(this, rootPaneCheckingEnabled);
        flogin.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FormSolicitacaoTarifa formTarifa = new FormSolicitacaoTarifa();
        formTarifa.setTitle("Solicitação de Tarifa/Custo");
        formTarifa.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        IncluirSolicitacaoTarifa tarifa = new IncluirSolicitacaoTarifa();
        this.setTitle("Rotina de inclusão de solicitação de tarifa/custo em execução.....");
        tarifa.start();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        FormTabTarifa formularioTarifa = new FormTabTarifa(this, rootPaneCheckingEnabled);
        formularioTarifa.setTitle("Solicitação de Tarifa/Custo");
        formularioTarifa.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        VerificarSituacaoSolicitacaoTarifa t = new VerificarSituacaoSolicitacaoTarifa();
        this.setTitle("Rotina De verificação da situação da Tarifa em execução.....");
        t.start();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        AnaliseLiberacaoCustoTarifa a = new AnaliseLiberacaoCustoTarifa();
        this.setTitle("Rotina de análise/liberação de Custo/Tarifa");
        a.start();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        EfetivarCustoTarifa ef = new EfetivarCustoTarifa();
        this.setTitle("Rotina de efetivação de tarifa em execução....");
        ef.start();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        DespacharCustoTarifa d = new DespacharCustoTarifa();
        this.setTitle("Rotina Despachar Tarifa/Custo em execução....");
        d.start();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    PartidaEgtCustoTarifa t = new PartidaEgtCustoTarifa();
                    t.inicioRotinaSisbb(sisbb, "EGT");

                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        };
        thread.start();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    VerificarSituacaoPartidaEgt t = new VerificarSituacaoPartidaEgt();
                    t.inicioRotinaSisbb(sisbb, "EGT");

                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        };
        thread.start();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        AcessoOutrosBancos a = new AcessoOutrosBancos();
        a.logarPortalRejud();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        FormSolicitacaoInedito formInedito = new FormSolicitacaoInedito();
        formInedito.setTitle("Solicitação de Inédito");
        formInedito.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    ColetaDadosUsuarios usuario = new ColetaDadosUsuarios();
                    usuario.inicioRotinaSisbb(sisbb, "ARH");
                    sisbb.rotinaEncerramento();

                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        };
        thread.start();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        Thread thread = new Thread() {

            @Override
            public void run() {//double a, String b, int c, Date k
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    TratarInedito t = new TratarInedito();

                    PropriedadesPadraoSISBB sis = new PropriedadesPadraoSISBB();
                    t.inicioRotinaSisbb(sisbb, "DJO");

                    // t.CapturaDetentoraDJO(sisbb, sis);//, a, b, c, k
                    sisbb.rotinaEncerramento();

                    JOptionPane.showMessageDialog(null, "Tratamento de inéditos finalizado");
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        };
        thread.start();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed

        ComplementarDeposito d = new ComplementarDeposito();
        this.setTitle("Rotina  de complementação de depósitos em execução....");
        d.start();


    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed

        VerificarRetornoAgencia d = new VerificarRetornoAgencia();
        this.setTitle("Verificando retorno agencia ....");
        d.start();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed

//        ColetaSaldoDjoBaseWebTESTE saldoDJO = new ColetaSaldoDjoBaseWebTESTE();
//        List<Desconciliacao> listaColetaSaldo = saldoDJO.createListTESTE();
//
//        //dividir lista       
//        List<List<Desconciliacao>> subLista = Utils.dividirListaPartes(listaColetaSaldo, 8);
//
//        for (List<Desconciliacao> novaLista : subLista) {
//
//            Thread thread = new Thread() {
//
//                @Override
//                public void run() {
//
//                    //inicio loop thread
//                    try {
//
//                        Janela3270 sisbb = new Janela3270();
//                        ColetaSaldoDjoBaseWebTESTE teste = new ColetaSaldoDjoBaseWebTESTE();
//                        teste.inicioRotinaAlternativa(sisbb, "DJO", novaLista);
//
//                    } catch (Throwable ex) {
//                        Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//
//                }
//
//            };
//            thread.start();
//
//        }

  
        
        
        Thread thread = new Thread() {

            @Override
            public void run() {//double a, String b, int c, Date k
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    ColetaSaldoDjoBaseWeb t = new ColetaSaldoDjoBaseWeb();
                    PropriedadesPadraoSISBB sis = new PropriedadesPadraoSISBB();
                    t.inicioRotinaSisbb(sisbb, "DJO");//, a, b, c, k
                    sisbb.rotinaEncerramento();

                    JOptionPane.showMessageDialog(null, "Captura Finalizada com Sucesso!");
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        };
        thread.start();

        
//        
//        Thread thread2 = new Thread() {
//
//            @Override
//            public void run() {//double a, String b, int c, Date k
//                try {
//                    Janela3270 sisbb = new Janela3270();
//                    sisbb.setTamanho(700, 500);
//                    ColetaSaldoDjoBaseWeb t = new ColetaSaldoDjoBaseWeb();
//                    PropriedadesPadraoSISBB sis = new PropriedadesPadraoSISBB();
//                    
//                    
//                    
//                    ColetaSaldoDjoBaseWebTESTE saldoDJO = new ColetaSaldoDjoBaseWebTESTE();
//                    
//                    List<Desconciliacao> listaColetaSaldo = saldoDJO.createListTESTE();
//                    List<List<Desconciliacao>> subLista = Utils.dividirListaPartes(listaColetaSaldo, 8);
//
//                    
//                    
//                    t.inicioRotinaAlternativa(sisbb, "djo", subLista);
//                    sisbb.rotinaEncerramento();
//
//                    JOptionPane.showMessageDialog(null, "Captura Finalizada com Sucesso!");
//                } catch (Throwable ex) {
//                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//            }
//
//        };
//        thread2.start();



    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed

        LeituraSaldoContabilPortal d = new LeituraSaldoContabilPortal();
        this.setTitle("Rotina  de leitura de saldo contabil base Web....");
        d.start();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed

       FormProgresso bar = new FormProgresso();
       bar.setVisible(true);


    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
      
        LeituraBaseDadosWEB d = new LeituraBaseDadosWEB();
        this.setTitle("Lendo dados complementar base WEB DJO");
        d.start();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
      
        ColetaResgateDepJudicial coleta = new ColetaResgateDepJudicial();
        coleta.start();
        
        
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        Thread thread = new Thread() {

            @Override
            public void run() {//double a, String b, int c, Date k
                try {
                    Janela3270 sisbb = new Janela3270();
                    sisbb.setTamanho(700, 500);
                    ColetarDadosDJOSequencial t = new ColetarDadosDJOSequencial();

                    PropriedadesPadraoSISBB sis = new PropriedadesPadraoSISBB();
                    t.inicioRotinaSisbb(sisbb, "DJO");

                    // t.CapturaDetentoraDJO(sisbb, sis);//, a, b, c, k
                    sisbb.rotinaEncerramento();

                    JOptionPane.showMessageDialog(null, "Coleta DJO sequencial finalizada!!");
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        };
        thread.start();
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        
        DestinarDesfavoravelDanoMoralDJO d = new DestinarDesfavoravelDanoMoralDJO();
        this.setTitle("Contabilização desfavoravel dano moral DJO");
        d.start();
        


    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
         DestinarDesfavoravelPoupancaDJO d = new DestinarDesfavoravelPoupancaDJO();
        this.setTitle("Contabilização desfavoravel Poupança DJO");
        d.start();
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        
        DevolverAgencia d = new DevolverAgencia();
        this.setTitle("Devolução agência");
        d.start();
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        VerificarSituacaoResgateBaseCpj d = new VerificarSituacaoResgateBaseCpj();
        this.setTitle("Sincronização situação dos resgates");
        d.start();
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        ComplementarDepositoEfetivacao d = new ComplementarDepositoEfetivacao();
        this.setTitle("Complementação de depósitos da efetivação");
        d.start();
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem43_retag691ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43_retag691ActionPerformed

        Thread thread = new Thread() {
            
            @Override
            public void run() {
                try {                    
                    
                    ColetaConta99 coleta99 = new ColetaConta99(ContaEnum.CONTA691);
                    coleta99.inicioRotinaSisbb("RETAG");
                    
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        };
        thread.start();  
        
    }//GEN-LAST:event_jMenuItem43_retag691ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        
        FormAtualizacao bar = new FormAtualizacao();
        bar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        FormProgressoUploadOB bar = new FormProgressoUploadOB();

        bar.setVisible(true);
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
       FormProgressoUploadOficio form = new FormProgressoUploadOficio();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
       
        FormProgressoRetab bar = new FormProgressoRetab();
        bar.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        
        FormAtualizacaoRetab bar = new FormAtualizacaoRetab();
        bar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem47_compe691ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47_compe691ActionPerformed
        
        Thread thread = new Thread() {
            
            @Override
            public void run() {
                try {                    
                    
                    ComplementoTFI tfi = new ComplementoTFI(ContaEnum.CONTA691);
                    tfi.preRotina();
                    
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        };
        thread.start();

     }//GEN-LAST:event_jMenuItem47_compe691ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        
        Thread thread = new Thread() {
            
            @Override
            public void run() {
                try {                    
                    
                    ColetaConta99 coleta99 = new ColetaConta99(ContaEnum.CONTA700);
                    coleta99.inicioRotinaSisbb("RETAG");
                    
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        };
        thread.start();
        
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jMenuItem49_compe700ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49_compe700ActionPerformed
        
        Thread thread = new Thread() {
            
            @Override
            public void run() {
                try {                    
                    
                    ComplementoTFI tfi = new ComplementoTFI(ContaEnum.CONTA700);
                    tfi.preRotina();
                    
                } catch (Throwable ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        };
        thread.start();
        
    }//GEN-LAST:event_jMenuItem49_compe700ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu18ContaJudicial;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23_retag700;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem43_retag691;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47_compe691;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49_compe700;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
